CC = g++
INC = ./inc 
EXE = TaskManager.out

$(EXE):
	$(CC) ./src/*.cpp -o $(EXE) -I$(INC)
	@echo "TaskManager.out build successfully.."
clean:
	rm -f $(EXE)
	@echo "Task Manager.out deleted successfully.."