CC = g++
INC = ./inc 
EXE = Task Manager.out

$(EXE):
	$(CC)./src/*.cpp -o $(EXE) -I$(INC)
	@echo "Task Manager.out build successfully.."
clean:
	rm -f $(EXE)
	@echo "Task Manager.out deleted successfully.."